Update CI conventions
inrupt/solid-client-notifications-js pull request #227
Opened 2022-03-29 12:34 UTC by NSeydoux

Apply CI conventions from our other repositories:
- NPM scripts naming scheme
- Audit and Lint workflow separate from the unit tests
- End-to-end tests separate from unit tests

This also fixes audit issues.

2022-03-29 14:18 UTC, ajacksified approved these changes

2022-03-29 15:35 UTC, ThisIsMissEm requested changes
The only one I'd like to request changes on is the docs scripts.

2022-03-30 09:08 UTC, NSeydoux commented on package.json
> +    "docs:preview": "npm run docs:build; cd docs/api; rm source/api/index.md; make html; cd ../; rm -r dist || true; mkdir -p dist/api; cp -r api/build/html/. dist/;",
There's no rush for this, I'll revert it.

2022-03-30 14:47 UTC, ThisIsMissEm approved these changes
Two minor comments, but looking good

2022-03-30 14:47 UTC, ThisIsMissEm commented on .github/workflows/ci.yml
>      - run: npx package-check
this is in lint / audit shared action already, iirc.

2022-03-30 14:47 UTC, ThisIsMissEm commented on .github/workflows/ci.yml
>      - name: Archive code coverage results
We don't need these two artifacts, they're never reused anywhere.

2022-03-30 14:48 UTC, ThisIsMissEm commented on .github/workflows/audit.yml
> +      uses: inrupt/javascript-style-configs/.github/workflows/reusable-audit.yml@create-reusable-workflows
Oh, also, these will break once that PR is merged, side-effect of using something in testing. Let's make sure these work then merge that branch

2022-04-01 09:46 UTC, merged