Mention server support restrictions, fix #59
inrupt/solid-client-notifications-js pull request #61
Opened 2021-05-04 13:21 UTC by michielbdejong

CC @nicolasmondada

2021-05-04 14:41 UTC, nicolasmondada requested changes
I adjusted the text to explain a bit more about the decision behind the current incompatibility.

2021-05-04 14:41 UTC, nicolasmondada commented on README.md
> +at different options to resolve this in a next version; see
```suggestion
This client only works with Inrupt's ESS, providing secure notifications over Websockets. Unfortunately, this is not compatible with websockets notifications implemented by other Solid servers like NSS, PSS, CSS, TrinPod, and DexPod. These servers websocket notifications they are based on [Solid Websockets API](https://github.com/solid/solid-spec/blob/master/api-websockets.md), a specification not recommended for secure messaging. We are looking at different options to help developers get their apps working securely across all Solid servers.
```

2022-04-09 20:19 UTC, ThisIsMissEm commented
@kay-kim @nicolasmondada do we want to accept this and add it to the main page of the documentation as an admonition much like what I did with access-grants? (I assume this is still relevant today)

2022-04-19 23:23 UTC, ThisIsMissEm commented
Closing this in favour of changes in #244 — note: this updates the docs, but leaves the readme as-is; The documentation is the source of truth, not the README

2022-04-19 23:23 UTC, closed without merging